version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "PabloLION"
    ignore:
      - dependency-name: "@xterm/xterm"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "vite"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "eslint*"
        update-types:
          - "version-update:semver-patch"
      - dependency-name: "prettier"
        update-types:
          - "version-update:semver-patch"
