name: Compatibility Tests

on:
  workflow_dispatch: {}
  workflow_call: {}
  release:
    types:
      - published
  push:
    tags:
      - "v*"
  schedule:
    - cron: "0 6 * * 3" # Wednesdays at 06:00 UTC

jobs:
  version-matrix:
    timeout-minutes: 60
    name: Compatibility smoke (${{ matrix.suite.label }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - label: oldest-supported
            runtime: node20
            react: 18.3.1
            typescript: 5.2.2
            eslint: 8.57.0
            prettier: 3.3.3
          - label: latest-supported
            runtime: node24
            react: 19.1.1
            typescript: 5.9.3
            eslint: 9.13.0
            prettier: 3.6.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "9"

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.suite.label }} compatibility smoke (React ${{ matrix.suite.react }} / TS ${{ matrix.suite.typescript }} / ESLint ${{ matrix.suite.eslint }} / Prettier ${{ matrix.suite.prettier }} / ${{ matrix.suite.runtime }})
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || github.event_name == 'schedule' || matrix.suite.label == 'latest-supported' }}
        run: >
          pnpm run compat:matrix
          -- --runtime ${{ matrix.suite.runtime }}
          --linter eslint-prettier
          --react ${{ matrix.suite.react }}
          --typescript ${{ matrix.suite.typescript }}
          --eslint ${{ matrix.suite.eslint }}
          --prettier ${{ matrix.suite.prettier }}
