name: Compatibility Tests (Popular Runtimes)

on:
  workflow_dispatch:
    inputs:
      run_baseline:
        description: "Run baseline lane (Node 20 + oldest stack)"
        type: boolean
        default: true
      run_latest:
        description: "Run latest lane (Node 24 + latest stack)"
        type: boolean
        default: true

jobs:
  runtime-smokes:
    name: Popular runtime compatibility matrix
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: "9"

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run baseline compatibility smoke
        id: run-baseline
        if: ${{ inputs.run_baseline }}
        continue-on-error: true
        run: pnpm run ci:compat:baseline

      - name: Run latest compatibility smoke
        id: run-latest
        if: ${{ inputs.run_latest }}
        continue-on-error: true
        run: pnpm run ci:compat:latest

      - name: Fail job if any lane failed
        if: ${{ always() && (steps.run-baseline.outcome == 'failure' || steps.run-latest.outcome == 'failure') }}
        run: exit 1
