name: Lint and Format

on:
  pull_request:
    branches:
      - main
      - development # Add other branches if necessary

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify the Node.js version you are using

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run format
        run: pnpm run format

      - name: Check for uncommitted changes
        run: git diff --exit-code
        id: git_diff

      - name: Fail if there are uncommitted changes
        if: steps.git_diff.outcome != 'success'
        run: |
          echo "There are uncommitted changes after running format. Please commit the changes and push again."
          exit 1
